apiVersion: v1
kind: Service
metadata:
  name: voiceforge-flower
  namespace: voiceforge-stt
  labels:
    app.kubernetes.io/name: voiceforge
    app.kubernetes.io/component: flower
spec:
  type: ClusterIP
  ports:
  - port: 5555
    targetPort: 5555
    protocol: TCP
    name: flower
  selector:
    app.kubernetes.io/name: voiceforge
    app.kubernetes.io/component: flower
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: voiceforge-flower
  namespace: voiceforge-stt
  labels:
    app.kubernetes.io/name: voiceforge
    app.kubernetes.io/component: flower
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: voiceforge
      app.kubernetes.io/component: flower
  template:
    metadata:
      labels:
        app.kubernetes.io/name: voiceforge
        app.kubernetes.io/component: flower
    spec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      imagePullSecrets:
      - name: voiceforge-registry-secret
      containers:
      - name: flower
        image: voiceforge/stt-flower:latest
        imagePullPolicy: IfNotPresent
        command:
        - celery
        - -A
        - app.worker
        - flower
        - --port=5555
        - --broker_api=redis://:$(REDIS_PASSWORD)@voiceforge-redis:6379/1
        ports:
        - containerPort: 5555
          name: flower
          protocol: TCP
        env:
        - name: FLOWER_BASIC_AUTH
          value: "admin:$(GRAFANA_ADMIN_PASSWORD)"
        envFrom:
        - configMapRef:
            name: voiceforge-config
        - secretRef:
            name: voiceforge-secrets
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "200m"
        livenessProbe:
          httpGet:
            path: /
            port: 5555
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 5555
          initialDelaySeconds: 10
          periodSeconds: 5
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          runAsUser: 1000
---
# ServiceMonitor for Prometheus scraping
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: voiceforge-metrics
  namespace: voiceforge-stt
  labels:
    app.kubernetes.io/name: voiceforge
    app.kubernetes.io/component: monitoring
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: voiceforge
  endpoints:
  - port: metrics
    interval: 30s
    path: /metrics
    honorLabels: true
  - port: http
    interval: 30s 
    path: /metrics
    honorLabels: true
  namespaceSelector:
    matchNames:
    - voiceforge-stt
---
# PrometheusRule for alerting
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: voiceforge-alerts
  namespace: voiceforge-stt
  labels:
    app.kubernetes.io/name: voiceforge
    app.kubernetes.io/component: monitoring
spec:
  groups:
  - name: voiceforge.rules
    rules:
    - alert: VoiceForgeAPIDown
      expr: up{job="voiceforge-api"} == 0
      for: 1m
      labels:
        severity: critical
      annotations:
        summary: VoiceForge API is down
        description: "VoiceForge API has been down for more than 1 minute."
    
    - alert: VoiceForgeHighLatency
      expr: histogram_quantile(0.95, rate(http_request_duration_seconds_bucket{job="voiceforge-api"}[5m])) > 0.5
      for: 5m
      labels:
        severity: warning
      annotations:
        summary: High request latency
        description: "95th percentile latency is above 500ms for 5 minutes."
    
    - alert: VoiceForgeHighErrorRate
      expr: rate(http_requests_total{job="voiceforge-api",status=~"5.."}[5m]) / rate(http_requests_total{job="voiceforge-api"}[5m]) > 0.05
      for: 2m
      labels:
        severity: warning
      annotations:
        summary: High error rate
        description: "Error rate is above 5% for 2 minutes."
    
    - alert: VoiceForgeHighMemoryUsage
      expr: container_memory_usage_bytes{container="api",namespace="voiceforge-stt"} / container_spec_memory_limit_bytes > 0.9
      for: 5m
      labels:
        severity: warning
      annotations:
        summary: High memory usage
        description: "Memory usage is above 90% for 5 minutes."
    
    - alert: VoiceForgeHighCPUUsage
      expr: rate(container_cpu_usage_seconds_total{container="api",namespace="voiceforge-stt"}[5m]) > 0.8
      for: 10m
      labels:
        severity: warning
      annotations:
        summary: High CPU usage
        description: "CPU usage is above 80% for 10 minutes."
    
    - alert: VoiceForgeWorkerDown
      expr: celery_workers_active{job="voiceforge-worker"} == 0
      for: 2m
      labels:
        severity: critical
      annotations:
        summary: No active Celery workers
        description: "No active Celery workers detected for 2 minutes."
    
    - alert: VoiceForgeQueueBacklog
      expr: celery_queue_length{job="voiceforge-worker"} > 100
      for: 5m
      labels:
        severity: warning
      annotations:
        summary: High queue backlog
        description: "Celery queue length is above 100 for 5 minutes."
    
    - alert: VoiceForgePostgresDown
      expr: up{job="voiceforge-postgres"} == 0
      for: 1m
      labels:
        severity: critical
      annotations:
        summary: PostgreSQL is down
        description: "PostgreSQL database has been down for more than 1 minute."
    
    - alert: VoiceForgeRedisDown
      expr: up{job="voiceforge-redis"} == 0
      for: 1m
      labels:
        severity: critical
      annotations:
        summary: Redis is down
        description: "Redis cache has been down for more than 1 minute."
    
    - alert: VoiceForgeHighTranscriptionFailureRate
      expr: rate(transcription_failures_total[5m]) / rate(transcription_requests_total[5m]) > 0.1
      for: 3m
      labels:
        severity: warning
      annotations:
        summary: High transcription failure rate
        description: "Transcription failure rate is above 10% for 3 minutes."
    
    - alert: VoiceForgeLowDiskSpace
      expr: (node_filesystem_avail_bytes{mountpoint="/app/models"} / node_filesystem_size_bytes{mountpoint="/app/models"}) < 0.1
      for: 5m
      labels:
        severity: warning
      annotations:
        summary: Low disk space for models
        description: "Available disk space for models is below 10%."
---
# PodDisruptionBudget for API pods
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: voiceforge-api-pdb
  namespace: voiceforge-stt
  labels:
    app.kubernetes.io/name: voiceforge
    app.kubernetes.io/component: api
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: voiceforge
      app.kubernetes.io/component: api
---
# PodDisruptionBudget for workers
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: voiceforge-worker-pdb
  namespace: voiceforge-stt
  labels:
    app.kubernetes.io/name: voiceforge
    app.kubernetes.io/component: worker
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: voiceforge
      app.kubernetes.io/component: worker